name: 自动部署
on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v4
        with:
          ref: main

      - name: 配置 AWS 凭证
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
          echo "AWS_EC2_METADATA_DISABLED=true" >> $GITHUB_ENV

      - name: 部署静态网站到 S3
        run: |
          aws s3 sync . s3://${{ secrets.AWS_BUCKET_NAME }} \
            --endpoint-url https://s3.bitiful.net \
            --delete \
            --exact-timestamps \
            --storage-class REDUCED_REDUNDANCY \
            --multipart-chunksize 64MB \
            --exclude ".git/*" --exclude ".github/*"
