name: 自动部署
on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v4
        with:
          ref: main

      - name: 配置 AWS CLI
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
          echo "AWS_EC2_METADATA_DISABLED=true" >> $GITHUB_ENV
          echo "AWS_CLI_MAX_UPLOAD_PARTS=64" >> $GITHUB_ENV   # 限制最大分片数量，加速上传
          echo "AWS_CLI_UNIFIED_CLI_HISTORY=0" >> $GITHUB_ENV # 关闭 CLI 历史记录，减少日志占用

      - name: 部署静态网站到 S3
        run: |
          aws s3 cp . s3://${{ secrets.AWS_BUCKET_NAME }} \
            --endpoint-url https://s3.bitiful.net \
            --delete \
            --exact-timestamps \
            --storage-class REDUCED_REDUNDANCY \
            --exclude ".git/*" --exclude ".github/*"
